@startuml

hide circle
skinparam inetype ortho

entity Lending {
    +id: int
    --
    #borrower_id: string
    #lender_name: string
    #content: string
    #has_returned: boolean
    #created_at: timestamp
    #udpated_at: timestamp
}

entity Example {
    +primary_key: type
    ~foreign_key: type
    #not null: type
}
note bottom: 上からそれぞれ<<PK>>, <<FK>>, <<NOT NULL>>を表す記号

@enduml
